### ISSUE TITLE
Detail 페이지 처리 방식에 대해서

### ISSUE THREAD

**Issue by Irelander** [skaiworks/prj-red-art-mall#15]
#### 개요
 상세 페이지의 처리 방식에 대해서 어떤 방향으로 구현 할지 정의가 필요하다.

#### 방안(시나리오)
  - URL ( queryParams) 을 활용
      - 사용시 발생 가능한 이슈 : 해당 id값 주소창에 노출된다.

  - RenderWithData 를 통해 참조값 전달
      - 사용시 발생 가능한 이슈 : 해당페이지는 웹 링크를 통해서만 이동이 가능하기 때문에 사용자들간의 url 공유가 불가능하다.

**Comment by meinzug** [comment]
사이트 특성상 ​URL 공유가 필요하므로 URL 방식으로 작업을 해야 할 것 같습니다.
이와 관련해서 Artist Indi, Artist Team, Product 스키마에 UUID 필드를 반영해 두겠습니다.
작업 후 공유하겠습니다.

ps. sequence number 로 하려 했는데, 게시판 처럼 게시순번이 필요하지 않아 심플하게 UUID 면 될것 같습니다.
