### ISSUE TITLE
공통적인 댓글관련 이슈

### ISSUE THREAD

**Issue by Irelander** [skaiworks/prj-red-art-mall#18]
#### 개요
   - 작품디테일 화면 구현중 댓글과 관련한 기술적 이슈

#### 현재 상황
   - Schema
````
Artwork =
  userId:         user's _id
  artworkCode:    아트웍 코드
  thumbnailUrl:   썸네일 url
  imageUrl:       이미지 url
  title:          제목
  desc:           설명
  tagList:        [tag, tag,,,] 태그들
  colorList:      [color, color,,,]

  commentList:    [{}, {},,,] 평가
    userId:       사용자 _id
    username:     아이디
    thumbnailUrl: 썸네일 url
    text:         댓글
    replyList:  [{}, {},,,]
      userId:       사용자 _id
      username:     아이디
      thumbnailUrl: 썸네일 url
      text:         댓글

  createdAt:  {}
  updatedAt:  {}
  removedAt:  {}
````
  - View 화면
      -  작품 디테일 화면 참조

#### 내용
   - 이미지첨부필요? 필수? 
   - 확인버튼 없음 -> 이미지첨부를 사용 안한다면 확인버튼으로 대체
   - 작성일자스키마 없음
   - 답글에 답글 불가능?
   - 삭제버튼 있는데 참조값?(uuid필요할듯..)
        - 시간을 초까지 비교하면 상관없지만 같은유저/같은내용 일경우 참조할 수 없다...

**Comment by Irelander** [comment]
화면 UI 상에서는 댓글에 댓글도 등록가능하도록 되어 있습니다.

**Comment by meinzug** [comment]
기획자분과 논의 해봤는데요.
아래와 같이 우선 정리가 되었네요.
(일부 세세한 부분은 퍼블리싱과 디자인이 다른 부분이 있기도 했네요.)

#### 이미지 첨부 관련
* 작품 상세 관련
  - 댓글은 이미지 청부 기능 삭제 (불필요)
  - 글쓰기 확인 버튼 필요
  - 대댓글 버튼 클릭시 페이스북 댓글 기능과 유사하게 댓글 영역 나타나도록 수정
  - 이 부분은 업데이트된 디자인 내용을 첨부해 주기로 했습니다.
* 상품 상세 관련
  - 댓글 영역에 이미지 첨부 기능 있는것이 맞음
  - 글쓰기 확인 버튼 필요
  - 대댓글 버튼 동작 위와 동일
  - 업데이트된 디자인 내용 참고

#### 작성일자 스키마
* 작성일자는 createAt {} 값으로 사용됩니다.

#### 대댓글 관련 스키마
- 관련 스키마들에 대해서 댓글 및 대댓글 작업이 가능 하도록 수정해 놓겠습니다.
- 형식은 document 안에 embeded document 스타일이면 될것 같습니다.
- uuid 관련 적용도 함께 해두겠습니다

작업 확인 후 close 하도록 하겠습니다~

**Comment by meinzug** [comment]
업데이트 디자인 작업을 올려 주셨네요.

#### 작품상세 및 댓글 화면
* https://trello.com/c/HHjRTbEa/50--

#### 상품상세 및 댓글의 경우
* https://trello.com/c/HHjRTbEa/50--

작업에 참고해 주세요.
