### ISSUE TITLE
아티스트 페이지 관련 논의 사항

### ISSUE THREAD

**Issue by Irelander** [skaiworks/prj-red-art-mall#2]
### 아티스트 페이지 구현관련 논의 주제 정리

* 좌측 Side-nav의 Sorting 기준에 대한 정의가 필요
  - 어떤 컬렉션에 대한 정렬인가
  - 어떤 필드를 기준으로 정렬할 것인가

* 소소한? 질문
  - 태크 출력시 어떤 기준으로 데이터를 불러올건지 (랜덤 or 많이 사용된 순)
  몇개까지 화면에 표시할 것인지( limit or infinity scroll)

  - 카테고리에 대해...
  - 정렬기준이 상품이라면 사용 가능
  - 아티스트 -> 아티스트의 카테고리가 포스터,스티커...? 어떤 의미의 카테고리?
  - 포트폴리오 -> 포트폴리오에 카테고리 적용? 작가의 그림 or 사진작품인데
                          작가가 작품등록시 어떤 상품에 적용하겠다고 선언하고 등록해야
                          가능한데, 포트폴리오에는 카테고리라는 항목이 무의미..
                          카테고리의 내용을 작품주제로 선정하고 메뉴항목을 바꾸면 사용
                          가능하지만 스키마 변경 필요

* 만약 데이터를 Product로 정 할 경우
  - 작가의 포트폴리오는 작가 개인페이지에서만 볼 수 있다?
  - header의 아티스트/상품 메뉴 구분이 되있는데 상품은 상품에서 볼 수 있는게 의미상 맞지않나..

* 스키마에 대한 질문
```
  artwork
    artworkCode ?
    status ? -> 포트폴리오도 관리자의 승인을 받아야 공개가 가능?
    thumbnailUrl & imageUrl 구분?
```

* 스키마에 추가 되어야 할 필드
```
  artwork
    if new category
      category

  users (아티스트 정보를 이곳에서 얻어온다면..)
    facebookUrl   -> 페이스북 링크
    twitterUrl    -> 트위터 링크
    introText     -> 아티스트 설명
    if (아티스트의 좋아요 옆에 있는 핀버튼 모양이 해당 아티스트 페이지의 공유 카운트라면)
      pinUserList  -> 나의 페이지 링크 가져간 유저정보
```
### Users 컬렉션을 Artist의 정보를 가져오는데 사용한다면 발생할 수 있는 이슈?
* 아티스트페이지에서 userType이 ARTIST인 데이터를 subscribe 해야한다. userId 노출될수있다.
  - 해결방안?
  - Meteor.method를 통해서 데이터를 가져와 call로 받아 핸들링
     : Reactive 데이터가 아니게 된다. -> Tracker를 이용해 수동으로 설정

### 논외
* 회원가입(아티스트 or 컴퍼니)시 3단계에서 파일업로드 후 취소나 브라우져닫기등 이탈시 S3에 쓰레기 파일 존재할 가능성
  - 해결방안?
  - 4단계 유저 생성시에만 Image컬렉션의 metadata.owner 의 값이 userId로 변경되기때문에
    4단계, 즉 유저생성이 되지 않은 상태라면 owner의 값이 이메일을 참조하고 있다.
    regex를 사용해서 owner의 값이 @를 포함하고 있는 도큐먼트들을 삭제하면 제거 가능하다.

**Comment by meinzug** [comment]
## 포트폴리오 상세보기 화면에 사용될 데이터 작업 필요

## 아티스트 정리
  - 다른 아티스트 정보도 열람해야 한다
  - 최신 순, 좋아요 순, 판매 순
  - 아티스트 설명 필요
  - 자기의 소셜 계정 정보 저장 필요
  - 나를 찜한 사람들 개수 필요
  - 카테고리는 하나만 선택 (mypage 내정보 관리)
  - 카테고리 스트링값 정의 필요
  - 좌측 하단 태그 영역은 삭제
  - 마이페이지 관리에서 카테고리 지정 하도록 추가
  - 좌측 카테고리 옵션은 아티스트 카테고리를 의미

## 기존 스키마에 artistInfo 만들어 저장
  - 필요한 필드를 모아 놓는 걸로

## 작품팝업
  - 설명
  - 원본 이미지
  - 댓글

## 작품등록 (디자인 필요)
  - 디자인 준비 중 (상품 등록 화면 활용 예정)
  - 태그 입력 기능

## 썸네일을 위한 스키마 생성 필요
  - 이미지 저장시 각각 insert. (Thumbnail, Image)

## 태그 나열 정책 필요
## 썸네일 이미지 URL 어떻게 하나
  - 일단 이미지 URL 과 같은 값으로 처리
  
## 아트웍
  - status 필드 삭제

## 아티스트, 작품 테스트 데이터 생성기 필요
  - 스키마 픽스 후

## 휴대폰 중복 검사 remote API 필요

**Comment by meinzug** [comment]
#### 클로즈 후 잔여작업은 다른 새 이슈로 이전
#### 잔여작업
* 아티스트에서 사용될 작품 데이터 생성기 필요
* 아티스트(개인,팀) 목록 반환 메소트 콜 필요
